# Generated by Django 5.2.3 on 2025-07-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='books',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reviews',
        ),
    ]
